const products = [
  {
    id: 1,
    name: "Mazda CX-9",
    price: 583.98,
    description: "4-day rental",
    // image: "./images/1.jpeg",
    tag: "Electronics",
    image: "https://img.freepik.com/premium-psd/3d-handbag_946288-346.jpg",
  },
  {
    id: 2,
    name: "Smartphone XYZ",
    price: 799.99,
    description: "6.5-inch display, 128GB storage",
    // image: "2.png",
    tag: "Phone",
    image: "https://clipart-library.com/image_gallery2/Shopping-Bag-PNG-HD.png",
  },
  {
    id: 3,
    name: "Laptop ABC",
    price: 1299.95,
    description: "Intel Core i7, 16GB RAM, 512GB SSD",
    // image: "3.png",
    tag: "Electronics",
    image: "https://img.freepik.com/free-psd/levitating-headphones-still-life_23-2150806967.jpg",
  },
  {
    id: 4,
    name: "Wireless Headphones",
    price: 149.99,
    description: "Bluetooth, Noise Cancelling",
    // image: "4.png",
    tag: "Headphones",
    image: "https://img.freepik.com/free-psd/levitating-headphones-still-life_23-2150806967.jpg   ",
  },
  {
    id: 5,
    name: "Fitness Tracker",
    price: 49.95,
    description: "Heart rate monitor, Step counter",
    image: "https://img.freepik.com/free-psd/levitating-headphones-still-life_23-2150806967.jpg",
  },
  {
    id: 6,
    name: "Coffee Maker",
    price: 79.99,
    description: "Programmable, 12-Cup Capacity",
    // image: "6.png",
    tag: "Electronics",
    image: "https://png.pngtree.com/png-clipart/20201223/ourmid/pngtree-clothing-sweater-clothes-clothing-mens-clothing-spring-clothes-foreign-trade-tailor-png-image_2611494.jpg",
  },
  {
    iid: 7,
    name: "Designer Watch",
    price: 299.99,
    description: "Stainless steel, Water-resistant",
    // image: "7.png",
    tag: "Clothing",
    image: "https://w7.pngwing.com/pngs/479/890/png-transparent-t-shirt-sweater-vest-crew-neck-cardigan-red-undershirt.png",
  },
];

export default products;
